_core/skin/dx3/list-chara.html, _core/skin/sw2/list-chara.html, _core/skin/sw2/list-item.html, _core/skin/sw2/list-mons.html
私のサーバで最新版のゆとシートを導入させていただきましたところ、一覧画面にて `./skin/js/list.js` が見つからない旨のエラーメッセージが出ているのを確認しました。
調査の結果パスを修正しましたので、PRを送らせていただきます。
=> list.jsのパス修正

_core/skin/_common/js/lib/ytsheetCommon.js, _core/skin/dx3/js/lib/ytsheetToUdonariumDX3.js, _core/skin/dx3/sheet-chara.html, _core/skin/sw2/js/lib/ytsheetToUdonariumSW25.js, _core/skin/sw2/sheet-chara.html, _core/skin/sw2/sheet-monster.html
FireFox から Udonarium の駒をダウンロードしようとすると https://github.com/yutorize/ytsheet2/blob/dc041639c2daf003345410a7c4024388c95df80c/_core/skin/_common/js/lib/ytsheetCommon.js#L97 で `e.currentTarget` が未定義とされて処理が停止する。
Google Chrome ではこの現象は発生しない。
event が格納された変数の挙動が両ブラウザで異なる？
（すみません、原因までちゃんと追えていないです）
注意書きには `IEは非対応です（推奨ブラウザ：Chrome／FireFox）。` とあるため、
FireFox / Google Chrome 双方で DL できる必要がある。
* 画像 DL の関数が共通化されていなかったので共通化
* `e.currentTarget` を別変数に入れておき、それを使うことで未定義になるのを防止
=> fix download for Udonarium data in FireFox

_core/lib/sw2/view-mons.pl
以下の添付画像のように SW のエネミーデータについて OGP 上の知名度が 知名度/知名度 と表示されます。   
これは 知名度/弱点値 を本来は意図しているのではないかと。弱点値を出すように変える PR です。
恐れ入りますが、ご確認をお願いします。
=> SW エネミーデータの OGP について 知名度：知名度/知名度 になっているのを 知名度/弱点値にする

_core/lib/dx3/convert.pl, _core/lib/sw2/convert.pl
* キャラクター保管所の URL に余計な文字列があったらコンバートが失敗する問題への対応
（例： https://charasheet.vampire-blood.net/4129510#top
　→ https://yutorize.2-d.jp/ytsheet/sw2.0/?url=https%3A%2F%2Fcharasheet.vampire-blood.net%2F4129510%23top ）
* SW2.X についてコンバートした際の作成時の初期値（経験点3000点やお金1200ガメル）が入らない問題への対応
SW2.X についてコンバートした際の作成時の初期値についてサーバの設定を用いるようにしています。
しかし、キャラクター保管所からコンバートする場合は常に経験点3000点やお金1200ガメルになるはずなので、
ここは固定の値を用いるべきかもしれない、と考えています。
見解・方針をお伺いしたく。
=> コンバート時の挙動修正提案

_core/skin/_common/css/sheet.css, _core/skin/_common/js/sheet.js
[iPhone 等からココフォリアのクリップボード機能が動かない問題](https://discord.com/channels/791236985116426271/791237812519043073/955311895127142491)への対応案です。
|端末|HTTPS|HTTP|
|----|----|----|
|iPhone等|`navigator.clipboard.write`|テキストエリアを表示し手動でコピーさせる|
|Windows等|`document.execCommand`|`document.execCommand`|
実際は次の挙動をします。
```javascript
if(navigator.clipboardが利用可能ならば) {
ClipboardItemを用いてnavigator.clipboard.writeを試みる
if(ClipboardItemを用いたnavigator.clipboard.writeが成功したら) {
終了
} else {
document.execCommand を用いた方法を試みる
if(document.execCommand を用いた方法が成功したら) {
終了
} else {
テキストエリアを表示して手動コピーさせる
}
}
} else {
document.execCommand を用いた方法を試みる
if(document.execCommand を用いた方法が成功したら) {
終了
} else {
テキストエリアを表示して手動コピーさせる
}
}
```
このコードは実際に以下環境で実動作させているため、挙動については以下からご確認いただけます。
https://hiyo-hitsu.sakura.ne.jp/ytsheets/ytsheet2_sw2.5/sw2.5/?id=k …
=> iOS でもココフォリアへのコマ作成を可能にする

_core/skin/_common/js/lib/ytsheetCommon.js, _core/skin/_common/js/sheet.js
> [「パスワードが間違っているか、編集権限がありません。」と表示された画面から「出力」の各種操作をこころみると、ただしく実行されない](https://discord.com/channels/791236985116426271/791237812519043073/997326445871386675)
　キャラクターシートを編集しようとした場合、 `https://yutorize.2-d.jp/ytsheet/some_system/?mode=edit&id=xxxxxx` にアクセスする。しかし、編集権限がない場合、一見 `https://yutorize.2-d.jp/ytsheet/some_system/?id=xxxxxx` にアクセスした時と同様にキャラクターシートが表示されながらも "パスワードが間違っているか、編集権限がありません。" とメッセージが表示される。
　この状態で json データを取得しようとした場合、今の挙動だと `https://yutorize.2-d.jp/ytsheet/some_system/?mode=edit&id=xxxxxx&mode=json` へのアクセスとなり、`mode` は `edit` として扱われる。そのため、json データは取得できない。
　その時点でアクセスしているページの `mode` の値に関わらず `./?id=xxxxxx&mode=json` にアクセスするように変更した。
　また、チャットパレットの取得についても同様の問題があったため、修正している。
> [FireFoxでのみココフォリア出力でエラー](https://discord.com/channels/791236985116426271/791237812519043073/997560203681734746) …
=> 出力にまつわる問題点の解消

_core/lib/dx3/edit-chara.js, _core/lib/dx3/edit-chara.pl
ルール定義は『レネゲイズアージ』p14。データの例は同書p24など。
* 「衝動」が選択されていれば、 `{その衝動名}、120%` が入力候補に表示される。
* 「衝動」が選択されていなければ、従来どおり。
「衝動」欄に応じて datalist を動的に操作する。
=> [DX3] エフェクトの「制限」欄の入力候補にアージエフェクト用のものを追加

_core/lib/dx3/edit-chara.js, _core/lib/dx3/edit-chara.pl
タイミング・技能・難易度・対象・射程・侵蝕値・制限……という一連の項目は、たいていの場合は候補からの選択のみで足りるようになっているが、侵蝕値だけは手入力するしかなかった。
入力作業において、これは非常にわずらわしい。（前後の項目が候補からの選択で足りることもあって、意識のオーバーヘッドが発生する）
よって、頻出する値を候補として提示し、改善を量る。
=> [DX3] エフェクトの「侵蝕値」に入力候補を提示する

_core/lib/subroutine.pl
コメントアウト記法をもちいたとき、その行の数だけ改行が表示上でのこるようになっていた。
（のを直す）
=> Fix: コメントアウト記法（ `//...` ）を使用したときに改行がのこらないように

_core/lib/dx3/calc-chara.pl
なお、この値の解決は保存時におこなわれているので、既存データには保存しなおさないと反映されない。
=> [DX3] Fix: 能力値の成長がない場合、表示画面の「経験点計算」の「能力値」が空欄になるのを修正

_core/lib/dx3/view-chara.pl
291行目ですでに設定されているので不要
```
});
}
$SHEET->param(Skills => \@skills);
my @loises;
```
=> [DX3] 不要なコードを削除

_core/skin/dx3/css/chara.css, _core/skin/dx3/sheet-chara.html
　（おそらくHTMLのレンダリング上で高さを確保するために出力されていた）全角スペースを削除し、代わりに _::before_ 疑似要素を利用。
　（HTML上からコピーするときに、入力されていないはずの全角スペースが入ってくるのが気持ちわるかったので）
=> [DX3] コンボの組み合わせ欄が空のときに全角スペースを出力しない

_core/lib/dx3/edit-chara.pl
　数式として読む場合、括弧内の各演算は加算でなければおかしい。
　（ `消費できる上限 - ( 消費の内訳 ) = 残り` というニュアンスの式なので、括弧部分の計算結果は消費の合計にならなければならない）
　（ `x - ( a - b )` を展開すると `x - a + b` になってしまう）
=> [DX3] Fix: 編集画面の経験点内訳の表示における数式の誤りを修正

_core/lib/dx3/edit-chara.js
なんか `Event` オブジェクトの `path` プロパティが存在しなくなってるっぽくて、そのせいでエラーになって処理が中断されてた。
=> [DX3] コンボの条件入力補助メニューが自動的に消えない不具合を修正

_core/lib/edit.pl
　画像が設定されているシートをエクスポートした JSON ファイルをインポートすると、初回の（＝インポート時の）編集画面でのみ画像が表示されてしまう。
　（このとき、そのまま保存しても画像が保存されるわけではない）
　JSON 内の `imageURL` にもとづいて表示されているっぽい。
　インポート時に、 `imageURL` を削除する。
=> Fix: JSONファイルからインポートしたとき、最初の編集画面でのみ画像が表示されてしまう不具合を修正

_core/lib/ar2e/subroutine-ar2e.pl, _core/lib/blp/subroutine-sub.pl, _core/lib/dx3/subroutine-dx3.pl, _core/lib/kiz/subroutine-sub.pl, _core/lib/sw2/subroutine-sw2.pl, _core/lib/vc/subroutine-sub.pl
　バーティカルバーから開始山括弧までのあいだに改行があってもルビ記法として解釈されてしまう（そして表示がこわれる）不具合を修正。
　次のような文字列をシート内に記入する。
```
文中にバーティカルバー｜を記述
後の行に適当な《エフェクト名》を記述
```
https://yutorize.2-d.jp/ytsheet/dx3rd/?id=c70xsX
=> Fix: あいだに改行があってもルビ記法として解釈されてしまう不具合を修正

_core/skin/dx3/css/chara.css, _core/skin/dx3/sheet-chara.html
　コンボを簡易的な表示に切り替えられるようにする。
　コンボ欄の右上に「簡易表示」「詳細表示」の切り替えをおこなうＵＩを設け、それをクリックするごとに両者を切り替える。
　（レイアウトはエフェクトの折り畳み操作ＵＩを踏襲）
　簡易表示のあいだは、コンボ名と組み合わせの内容のみを表示する。
　デフォルトは「詳細表示」相当。（従来どおりの表示）
　コンボの数が多い、または個々の内容が長い場合でも、キャラクターの全体的な把握を容易にする。
　（コンボ欄が伸びるとページ全体の高さのうちかなりの割合を占めることになって、全容を把握しづらい）
=> [DX3] コンボを簡易的な形式で表示する機能を追加

_core/skin/dx3/css/chara.css, _core/skin/dx3/sheet-chara.html
↓300%拡大
効果行の tr の border-top が見えているせい
=> [DX3] 末尾のエフェクトの下側に余計なボーダーがあるように見えるのを修正

_core/lib/dx3/view-chara.pl
　シンドロームがひとつも選択されていないとき、表示画面で「ブリード」の文字のみが表示されていた。（次の画像のように）
　これはとくに意味を有さない表示であり、また非オーヴァードのキャラクターを表現したい場合などには明確に不自然なので、欄を空として表示するように。
=> [DX3] 「ブリード」に有効な値がないとき、表示を空にする

_core/lib/sw2/list-making.pl
　種族データが見当たらないと `$dicetotal` が `0` になってゼロ除算になって死ぬ。
　142行目の
```
AVERAGE => $dicetotal ? sprintf("%.5g", $average) : '―',
```
　を見るに、 `$dicetotal` が `0` となる可能性は想定されているっぽく、実際とくに問題なく動くっぽいのでこれでよさげ。
=> [SW2] Fix: 種族データが失われていても「キャラクター能力値作成」のログをとりあえず表示できるように

_core/lib/dx3/edit-chara.pl
ロイスの「関係」欄に入力候補を設定いただければと思っております。
キャラクター保管所からのコンバート時にも、こちらに「Dロイス」として自動入力されることから(下記)、欄の用途や表記はあっている認識でおります。
https://github.com/yutorize/ytsheet2/blob/f5233a818609bba93a9f090df9f565e3f7071bc9/_core/lib/dx3/convert.pl#L146
その上で、よく入力されるであろう「Dロイス」は入力候補にあると便利と考えたため提案させていただきます。
ご検討よろしくお願い致します。
動作確認：
// #61 をブランチ誤りに気づき再作成したPRになります
=> [DX3] ロイスの「関係」に入力候補を設定

_core/skin/sw2/css/arts.css, _core/skin/sw2/css/item.css, _core/skin/sw2/css/monster.css
魔物・アイテム・流派／神格データの作者名表示欄について、親の50％を超える場合にはそれに合わせて可変するように。
（たとえば個人名とサークル名を併記するなど、わりと超えるケースがある）
=> [SW2] 魔物・アイテム・流派／神格データの作者名の幅を可変にする

_core/lib/sw2/palette-sub.pl
一部の妖精魔法の「クリティカル値12かつ物理ダメージ」という挙動を、自動生成チャットパレットにおいてサポートする。
- 【アースハンマー】（『Ⅱ』191頁または『ＭＡ』132頁）
- 【ジャイアントキック】（『Ⅲ』174頁または『ＭＡ』133頁）
（一部といえば一部だが、多用に値する性能のデータなので、自動生成でサポートされていてほしい）
森羅魔法用の変数 `物理魔法D修正` を本件においても利用する。
“「妖精魔法」かつ「土属性を契約している」かつ「威力10または威力50」”の場合、Ｃ値12・物理ダメージ用のコマンド**も**出力する。
威力10は【ウィンドカッター】や【ファイアボルト】、威力50は【ファイアジャベリン】と区別がつかないので、通常の魔法ダメージ用のコマンドも依然として出力する。
=> [SW2] 特異な妖精魔法のダメージ算出コマンドをチャットパレットでサポート

_core/lib/sw2/edit-mons.pl
`.mount-only` class による非表示化の実装（ `display: none;` ）が、 `style` 属性によって上書きされていた。
=> [SW2] Fix: 魔物データの編集画面において、「現在の騎獣レベルの～」のくだりが騎獣でない場合にも表示される不具合を修正

_core/lib/sw2/edit-mons.js
以下の手順を連続して（＝途中で保存やリロードなどをせずに）おこなう。
1. 魔物データの新規作成を開始する
2. 騎獣モードに切り替える
3. 適正レベルの下限値に適当な値（例： 1 ）を入力する
4. 適正レベルの上限値に、下限値よりも大きな適当な値（例： 2 ）を入力する
5. 部位ごとのデータの、適正レベル下限値ではないレベル（前述の例でいえば 2 レベル）の、命中力の欄に適当な値（例： 1 ）を入力する
6. undefined 参照が発生する
`oninput="calcAcc(1-2)"` のような属性が設定され、実行時には `1-2` の部分が式として解決されてしまうため、存在しない要素が参照される。
`oninput="calcAcc('1-2')"` のようにパラメータをクォートでくくって文字列とする。
=> [SW2] Fix: 騎獣データの作成において、特定手順で undefined 参照が発生する不具合を修正

_core/lib/sw2/json-sub.pl
一定の条件下の魔物／騎獣データをゆとチャに自動入力すると、生命・精神抵抗力の値が適切に表示されない。
具体的には、空文字列で表示されたり（部位数を問わず魔物の場合はこれ）、末尾の部位の値が表示されたり（複数部位の騎獣の場合はこれ）していた。
* 複数部位の魔物
* 複数部位の騎獣
* 単一部位の魔物
※単一部位の騎獣は問題なかった
修正のついでに、魔物の場合は括弧書きで固定達成値も表示するようにしておいた。
（そのほうがルールブック上の表現にちかいので）
=> [SW2] Fix: 魔物・騎獣のデータをゆとチャに対して自動入力するとき、生命・精神抵抗力の値が適切に表示されない場合がある不具合を修正

_core/skin/sw2/css/monster.css
=> [SW2] 魔物データの部位セクションと特殊能力セクションの間の余白を大きくする

_core/lib/ar2e/edit-chara.pl, _core/lib/blp/edit-chara.pl, _core/lib/dx3/edit-chara.pl, _core/lib/gs/edit-chara.pl, _core/lib/kiz/edit-chara.pl, _core/lib/ms/edit-chara.pl, _core/lib/ms/edit-clan.pl, _core/lib/sw2.0/edit-chara.pl, _core/lib/sw2/edit-arts.pl, _core/lib/sw2/edit-chara.pl, _core/lib/sw2/edit-item.pl, _core/lib/sw2/edit-mons.pl, _core/lib/vc/edit-chara.pl, _core/skin/_common/css/edit.css
編集保護設定のコントロール群のコンテナに p 要素がもちいられていたが、意味的に妥当でないので、より妥当な fieldset 要素に置き換え。
_core/skin/_common/css/edit.css に対する変更は、 Chrome のクライアントスタイルシートの解除と、元の p 要素と同等のスタイルを適用することが目的。
=> 編集保護設定のコントロールのコンテナを p から fieldset に置き換え

_core/lib/dx3/json-sub.pl
=> [DX3] JSON出力時、Ｅロイスはロイス数に計上しない

_core/lib/dx3/convert.pl
キャラクターシート倉庫からのコンバート時、 D ロイスと同様の考慮を E ロイスについても適用する。
=> [DX3] キャラクターシート倉庫からのコンバートに際してＥロイスを考慮する

_core/skin/dx3/sheet-chara.html
ピュアブリードやクロスブリードには、「オプショナルシンドローム」という概念が存在しないため。
---
公式のキャラクターシートには常に「オプショナルシンドローム」の見出しがあるが、これは媒体が印刷物であることを前提としたものだと考える。ウェブアプリとしては不要なものは表示しないほうが自然なはず。
=> [DX3] トライブリードでないとき、「オプショナル」の見出しを表示しない

_core/skin/sw2/css/edit.css
バトルダンサーの宣言特技枠追加の選択欄において、今までは _optgroup_ のグループ名だけ表示されていた。（画像参照）
空の _optgroup_ が表示されても意味がないので、これを非表示にする。
（これが通常の特技枠であるのなら空のグループが表示されてもよいかもしれないが、バトルダンサーが得るこれは、ルール記述上「宣言特技枠」「宣言特技枠追加」（『ＢＭ』６頁）であり、宣言特技以外の選択肢がありえないことが自明である）
=> [SW2] バトルダンサーの宣言特技枠において常時特技・主動作特技の optgroup を表示しない

_core/lib/sw2/edit-mons.js
公式の文書（例：『Ⅲ』268頁や『ＥＴ』156頁）に倣うと、騎獣の２つ目以降の部位の抵抗力は「―」表記なので、デフォルト値をそれに合わせる。
=> [SW2] 騎獣の部位の追加において、生命・精神抵抗力のデフォルト値を `―` にする

_core/skin/dx3/css/chara.css, _core/skin/dx3/sheet-chara.html
---
* ロイスの属性は後発サプリメント（『リンケージマインド』）による追加ルールであり、採用していないセッション環境が現実的にありうる。
* ロイスの属性は、ルール上はタイタスの効果に対してのみ作用するため、（原則としてタイタスの効果を得られない）NPCにとっては属性の概念が不要である。
上記の理由から、属性の指定されているロイスがひとつもない場合は、属性の列そのものを非表示にするように。
---
_td_ を明示的に閉じているのは、 `:empty` を検出するためです。
=> [DX3] 属性つきロイスがひとつもない場合は、属性の列を表示しない

_core/skin/sw2/css/item.css, _core/skin/sw2/sheet-item.html
空の備考欄が表示されるのは据わりがわるいし無意味なので
---
**td** を明示的に閉じるようにしたのは、そうしないと `<td>` の後にある空白文字が要素内に含まれて `:empty` にならないからです。
=> [SW2] アイテムデータの武器・防具としてのデータを表示するテーブルの「備考」欄が空ならその列そのものを非表示にする

_core/skin/dx3/css/chara.css, _core/skin/dx3/sheet-chara.html
状態をもつロイスがひとつもなければ、「状態」の列見出しに意味はないので
=> [DX3] 有意なロイスの状態の指定がひとつもなければ、状態の見出しテキストを非表示にする

_core/lib/sw2.0/edit-chara.pl, _core/lib/sw2/edit-chara-datalist.pl, _core/lib/sw2/edit-chara.pl
　キャラクター編集画面の _datalist_ が、 2.0 と 2.5 でほとんど同様であるはず（というか現状は完全に一致する）にもかかわらず、双方に重複して存在していたのを統合。
=> Refactor: extract datalist from SW2 character edit script

_core/lib/sw2/palette-sub.pl
武器名に `[刃]` `[打]` `[魔]` のいずれかないし複数が含まれている場合、それをダメージ算出コマンドにも含める。
従来も命中力判定のコマンドには含まれていたが、これらの記号の意味するところが影響するのはむしろダメージ算出のほうなので。
BCDice 用のチャットパレットは、威力解決コマンドにアイテム名がそのまま含まれていた（それによって武器の性質も含まれていた）ので、ゆとチャ用のコマンドにのみ反映されるようにした。
=> [SW2] 近接攻撃・遠隔攻撃の威力解決コマンドに刃武器・打撃武器・魔法の武器の区分を明示する

_core/lib/dx3/edit-chara.pl
9c7e48dddc2235444762d109aa7c4d303170d56d によって「エンブレム／一般」「リレーション／一般」が追加されたが、『アイテムアーカイブ』を採用していない環境においては、そのたぐいのアイテムは「～／その他」という種別をもつので、それをサポートする意図。
「エンブレム／～」は『ユニバーサルガーディアン』が初出、「リレーション／～」は『ヒューマンリレーション』が初出です。
『アイテムアーカイブ』によってエンブレムデータとリレーションアイテムはすべて再録されましたが、同書が後発のサプリメントであり、採用していないセッション環境が現実的にある（なんならたぶんそっちのほうが多い）ことをかんがみると、『ＩＡ』前の環境向けの入力候補も存在すべきだという考えです。（ https://github.com/yutorize/ytsheet2/pull/71 が置き換えではなく追加だったのも同じ考えによるものです）
=> [DX3] アイテムの種別の候補に「エンブレム／その他」「リレーション／その他」を追加

_core/lib/sw2/edit-mons.pl, _core/skin/sw2/css/monster.css, _core/skin/sw2/sheet-monster.html
魔物の部位一覧の見出し行において、常に「攻撃方法（部位）」と表示されていたが、単一部位の魔物の場合には「（部位）」を表示しないようにする。
理由：
* 公式文書においてもそのような書式になっている
* 単一部位の場合には実際に意味がないし、単一部位の魔物はふつう攻撃方法のみを表記されるため、「（部位）」という見出しが事実に反することになる
**閲覧画面**
---
編集画面では、部位数にかかわらず「（部位）」を表示する。
（編集中は部位の数が未確定であり、判断がつかないため）
=> [SW2] 単部位の魔物の場合は、閲覧画面上で「攻撃方法」の後の「（部位）」を表示しない

_core/skin/sw2/sheet-arts.html
他のデータ区分（キャラクター・魔物・アイテム）のページではヘッダの h1 要素部分からその区分のトップに飛ぶが、魔法/神格/流派にかぎりそうなっていなかったのを修正。
=> Fix: [SW2] 魔法/神格/流派画面のヘッダの h1 要素のリンク先を修正

_core/lib/sw2/list-making.pl, _core/skin/sw2/index.html
キャラクター・魔物・アイテムの個別データのぺージなどと同じ感覚で、能力値作成の結果ページのヘッダからは能力値作成のトップに飛ぶように変更。
=> [SW2] 能力値作成の個別の結果ページ内のヘッダの h1 要素からは能力値作成のトップに飛ばす

_core/lib/sw2/view-chara.pl, _core/skin/sw2.0/sheet-chara.html, _core/skin/sw2/css/chara.css, _core/skin/sw2/sheet-chara.html
フェロー画面からＰＣ画面にもどるためのボタンが致命的にわかりづらかった。
当該機能をもつボタンのラベルが「通常」となっており、なにを意味するのかまったくわからなかった。
（「通常」という表現は、そうでない具体的ななにかと組でもちいないかぎり、何に対する“通常”なのかが特定できない。フェローに対する元キャラクターデータを“通常”と称するような慣習もないはず）
当該ボタンのラベルを「ＰＣデータ」に変更した。
合わせて、ＰＣ画面からフェロー画面に遷移するためのボタンも、「フェロー」から「フェローデータ」に変更した。
「フェローデータ」という表現は、編集画面におけるそれとも一致しており、妥当だと考えられる。
（他方、逆のボタンは、編集画面に合わせるならば「ＰＣデータ」より「キャラクターデータ」となるところだが、フェローもキャラクターであるため、その機能のボタンにもちいるには明瞭でないと考える）
=> [SW2] ＰＣデータ／フェローデータの切り替えボタンをよりわかりやすい表現に置き換える

_core/skin/sw2/css/chara.css, _core/skin/sw2/img/hexagon_light.svg, _core/skin/sw2/img/hexagon_night.svg
従来は CSS で実装されていた六角形のあしらいを、 SVG での実装に置き換える。
従来のあしらいはガタガタしていた。
まあこれだけなら調整であるていど誤魔化せなくもないかもしれないが、そもそもこういった歪みが発生するのは CSS で強引に実装していることに由来するものであり、画像にしてしまったほうが安定するはず。
SVG なら実質的にテキストデータなので軽量であり、またベクターデータであるので拡縮にも堪える。
**before**
**after**
**after / 拡大500%**
=> [SW2] フェローのレベルのあしらいの六角形を SVG での実装に置き換える

_core/lib/edit.pl, _core/lib/sw2/calc-chara.pl, _core/lib/sw2/edit-chara.pl
フェロー行動表内の「行動」「効果」で複数行を取り扱えるようにする。
（『DX3』の「コンボ」の解説欄と同様の挙動）
『SW2』におけるキャラクターの行動は、しばしば複数の要素が併用され（典型的な例は、宣言型の戦闘特技や、【ターゲットサイト】等の補助動作で使用できる自己強化能力）、またその効果もしばしば複雑になる。
フェローにおいてもそれは（程度の差はあるかもしれないが）同様であり、フェロー行動表の「行動」「効果」を単一行で記述するには難のあるケースがありうる。
一例として、『Ⅰ』236・237頁の「記入例」では「内容」が３行、同240頁の「記入例」では「内容」が４行・「効果」が３行ある。
『Ⅰ』240頁の記入例相当の内容：
従来でも、最終的な表示は（自動的な折り返しによって）複数行にわたることができたが、『Ⅰ』232～240頁の記入例を見るに、改行位置をコントロールできるほうがより望ましいと思われる。
（ルールブックの記入例は、（若干の例外はあるものの）意味的な単位と行の対応が意識されていると思われる）
=> [SW2] フェロー行動表の「行動」「効果」において複数行を記入できるように

_core/lib/dx3/view-chara.pl
https://github.com/yutorize/ytsheet2/pull/123 より復旧
---
DX3 のセッション履歴において、経験点の欄が空で、「適用」もチェックされていないとき、閲覧画面では空の _s_ 要素が発生していた。
（開始前～継続中のセッションなどの場合、経験点欄が（一時的に）空になっていることは現実的にありうる）
明確な実害はないが、  HTML としては不自然なので、経験点欄が空のときは `<s>` 要素でくくるのをやめる。
=> [DX3] セッション履歴において空の経験点を <s> 要素で括らないように

_core/lib/ar2e/json-sub.pl, _core/lib/blp/json-sub.pl, _core/lib/dx3/convert.pl, _core/lib/dx3/edit-chara.js, _core/lib/dx3/edit-chara.pl, _core/lib/dx3/json-sub.pl, _core/lib/edit.pl, _core/lib/gs/json-sub.pl, _core/lib/json.pl, _core/lib/kiz/json-sub.pl, _core/lib/ms/json-sub.pl, _core/lib/sw2/edit-chara.js, _core/lib/sw2/json-sub.pl, _core/lib/sw2/view-chara.pl, _core/lib/vc/json-sub.pl, _core/skin/dx3/css/edit.css
* 修正前：技能レベル10以上で表示
* 修正後：技能レベル11以上で表示
『2.5』においてデーモンルーラー技能で命中力判定をおこなうには、レベル11の魔法【デモンズブレード】が必要であるため。
（⇒『モンストラスロア』37頁）
閲覧画面においてはそもそもレベルの検証がなかったようなので、検証自体を追加した
=> [SW2.5] Fix: デーモンルーラーの命中力判定の行を表示する条件を修正＆閲覧画面にも同様の条件を適用

_core/lib/sw2/view-chara.pl
=> [SW2.5] 冒険者ランクをもたないキャラクターであればランクを（空ではなく） `―` と表示する

_core/lib/sw2/calc-chara.pl, _core/lib/sw2/edit-chara.js, _core/lib/sw2/view-chara.pl
「制限移動」の距離は移動力を超えることはないというルールがある（⇒『Ⅱ』58頁）が、それが考慮されていなかった。
（つまり、移動力が３（※《足さばき》下では10）を下回る状態でも、３（10）が制限移動の欄に表示されていた）
現実にそのようなキャラクターが運用されるのかはともかくとして、
* ドワーフ（⇒『Ⅰ』67頁）
* 学者生まれ（⇒『Ⅱ』28頁）
* 作成時の能力値の「Ｂ」が１
* アビスカース「鈍重な」（⇒『Ⅱ』284頁）の効果を受ける
というような条件で、移動力が３を下回るケースはルール上ありうる。
なお、《足さばき》を仮定すれば、移動力が制限移動の「10」を下回るケースはより簡単に発生しうる。
制限移動の距離が移動力を超えないように。
_view-chara.pl_ に対する処理は、すでに存在するデータへの補正。
（制限移動距離の計算は保存時になされるため、すでに存在するデータには本来の修正が（ふたたび保存されるまで）適用されない）
=> Fix: [SW2] 制限移動距離が移動力を超えないように

_core/lib/sw2.0/edit-chara.pl, _core/lib/sw2/edit-chara-datalist.pl, _core/lib/sw2/edit-chara.pl
名誉アイテムの名称入力欄に、括弧のための _datalist_ を設定
* `〈〉`：一般的なアイテム全般（典型的には流派アイテムなど）
* `【】`：流派、秘伝魔法
* `《》`：秘伝
=> [SW2] 名誉アイテムの名称欄に、括弧の入力候補を追加

_core/skin/sw2/sheet-arts.html
神格データの「格言」のうち、入力されていない欄がある場合、閲覧画面では空の鉤括弧が表示されていた。
これは不格好なので、入力されていない欄のものは表示しないようにする。
=> Fix: [SW2] 神格データの「格言」において、入力されていないものは表示しない

_core/lib/sw2/edit-arts.pl
独立した魔法データでは「消費」の入力候補が存在したが、秘伝魔法からは参照されていなかった
=> [SW2] 秘伝魔法の「消費」にも入力候補を提供する

_core/lib/sw2/edit-arts.pl
独立した魔法データでは「消費」の入力候補が存在したが、神格に付随する特殊神聖魔法からは参照されていなかった
=> [SW2] 特殊神聖魔法の「消費」にも入力候補を提供する

_core/lib/sw2/palette-sub.pl
【ショック】（⇒『Ⅲ』146頁，『ＭＡ』74頁）用のコマンドをプリセットに出力するように。
真語魔法12レベル、威力30の**物理**ダメージを発生させる
=> [SW2] チャットパレットのプリセットにおいて【ショック】用の威力表コマンドをサポート

_core/lib/view.pl, _core/skin/_common/css/sheet.css
従来は、数字列（厳密には「カンマを含む数字列」）の途中で改行（折り返し）が発生する場合があった。
例（ `5,890` のカンマの前で折り返されている）：
これは数値を読み取るうえで不便なので、カンマを含む数字列の途中に折り返しが発生しないようにする。
=> セッション履歴の数値項目において、数字列の途中で改行されないように

_core/skin/sw2/css/chara.css, _core/skin/sw2/sheet-chara.html
“穢れ”を１点以上もつキャラクターであれば、そのフェローデータ画面においても“穢れ”の値を表示する。
- とくに後天的な“穢れ”であれば、キャラクター性に寄与している場合がすくなからずある。
- 『バルバロスレイジ』によって蛮族のキャラクターを利用することが大きく増えるという想定のもと、フェローが蛮族である場合もまた想定され、（フェローは不利益効果を受けないとはいえ）“守りの剣”の影響を意識するようなセッションでは、キャラクター表現上でフェローの“穢れ”を意識することに意義がありうる。
- （2024/07/17 16:57追記）〈穢れの一撃加工〉（⇒『バルバロスレイジ』64頁）や［吸精］（⇒『アーケインレリック』16頁）など、“穢れ”の値によって効果量が変わるデータが一部存在し、それがフェローデータから参照される可能性がある。
=> [SW2.5] “穢れ”のあるキャラクターの場合、フェローデータの閲覧画面にも“穢れ”を表示する

_core/lib/sw2/edit-chara.js, _core/skin/sw2/css/edit.css
習得していない技能の存在を前提とする選択肢があっても実質的な意味がないので
=> [SW2] セージ／バードを習得していなければ言語の選択欄において当該技能のものを表示しない

_core/lib/sw2/edit-arts.pl
=> [SW2] Fix: 流派データをコンバートしようとしたときに、元データの流派名にかかわらず「無題」と表示される不具合を修正

_core/lib/ms/edit-clan.pl
=> [MS] Fix: クランデータをコンバートしようとしたときに、元データのクラン名にかかわらず「無題」と表示される不具合を修正

_core/lib/gc/edit-country.pl
=> [GC] Fix: 国データをコンバートしようとしたときに、元データの国名にかかわらず「無題」と表示される不具合を修正

_core/lib/sw2/subroutine-sw2.pl
魔物データにおいて、ＭＰをもたない魔物（部位）であれば、セッションツールへの出力にＭＰを含めないように。
実質的に意味のない項目が出力されることによって、セッションツール上でよけいな面積を占有するような事態を避けるため。
たとえば「ドラゴンフォートレス」（⇒『モンストラスロア』166頁）のような魔物データを作成し、ゆとチャadv.にポーティングした場合、次のようになる。
意味のないステータス項目が７つも発生しており、ゆとチャ上での参照性などに問題をきたすことがままある。
（これとはべつに、まあ有意なＭＰをもつ部位がたくさんある魔物だと依然としてかなり面積をとってしまうという問題はあるのだが、それは有意な項目がある以上はあるていど仕方がないものとして、置いておく。本件は、「省略可能なものは省略しておいたほうが便宜に資する」という意図）
=> [SW2] ＭＰをもたない魔物の場合は、セッションツールへの出力時にＭＰを除外する

_core/lib/sw2/view-mons.pl
- 必要でなさそうなときは単位 `G` をつけない
- 末尾の括弧書きは単位の後ろに回す
従来は、騎獣の価格に常に単位 `G` がついていた。
が、金額以外のものが記入されたときに不自然なことになるので、価格（の末尾）が数字でなければ単位をつけないようにした。
なお、金額以外のものが入力される具体例としては、（2.0時代の表現だが）『ルミエルレガシィ』137頁の「レンタル不能」などが考えられる。
`（非売品）` など、末尾に括弧書きがある場合、その部分を単位より後ろに回すようにした。
該当する表現の例は、やはり『ルミエルレガシィ』137頁などにある。
=> [SW2] 騎獣の価格に数値以外のものが入力されている場合に適切に整形する

_core/lib/subroutine.pl
- `m` を男として判定するように
- `f`, `fem` を女として判定するように
=> 性別の英語略記に対応

_core/skin/sw2/css/chara.css, _core/skin/sw2/sheet-chara.html
フェローデータの閲覧画面において、プレイヤー名が空であるなら、項目ごと表示しない。
（通常は「名前」と「種族」のあいだに「プレイヤー名」が存在するのだが、それがなくなっている）
主に、「シナリオに付属するＮＰＣをフェローとして実装する」ようなケースを想定している。
このような運用は本来的なフェロールールの想定の外ではある（フェローは「ＰＣ」を元とするものである，『Ⅰ』217頁）が、
- 「データを有し、協力的にゲームに寄与するＮＰＣ」を実装するにあたって、それなりの規格化がなされているフェロールールはそれなりに都合がよく、実際にそのように作られるシナリオはある
- 公式文書においても、シナリオ型サプリメントのたぐいでフェローデータが収録されたことがある
という事情をかんがみると、「ＰＣを母体としないフェロー」は現実的な需要として存在すると考えられる。
そのようなケースにおいて、そのフェローには、ふつう“プレイヤー”が存在しないのであるから、プレイヤー名の表記は必要が生じない。（制作者は制作者であって、そのフェローのプレイヤーではない）
よって、プレイヤー名の項目を表示しないほうが妥当であると考える。
あくまで「記入されていなければ表示しない」という挙動であるので、一般的な（ＰＣを母体とする）フェローには悪影響はなく、また「当初からＮＰＣとしてつくるフェローに（なんらかの理由で）“プレイヤー名”を表記したい」という需要も妨げることはない。
=> [SW2.5] フェローのプレイヤー名が空なら表示しない

_core/lib/sw2/view-mons.pl
「魔物データの命中力が空か `―` であり、かつ、打撃点がデフォルト値である」なら、打撃点を `―` に置き換える挙動を追加。
命中力が `―` （空）であるなら、その魔物（部位）は近接攻撃能力をもたない（⇒『Ⅰ』433頁，『ＭＬ』61頁）ため。
また実際のところ、命中力が定義されていない時点で打撃点があってもそれは無意味であるため。
ルール上は、命中力が空であるかぎりは問答無用で置き換えていいような気はするが、ユーザー作成のデータにおいて「近接攻撃能力はもたないが、打撃点のみ定義されており、特殊能力から参照する」ようなものがすでに作られていないとは断言できないため、後方互換性を考慮してデフォルト値 `2d+` でなければ置き換えないようにした。
=> [SW2] 魔物データの命中力が空か `―` であり、かつ、打撃点がデフォルト値なら、打撃点を `―` に置き換える

_core/lib/sw2/json-sub.pl
=> [SW2.5] Fix: sheetDescriptionM に冒険者ランク〈始まりの剣〉の★の数が含まれていなかったのを修正

_core/lib/sw2/palette-sub.pl
単一部位の魔物であれば、チャットパレットに部位名・攻撃手段を出力しないように。
たとえば次のような魔物を仮定したとき、
従来は
```
命中力／武器 2d+3+{命中修正}
ダメージ／武器 2d+2+{打撃修正}
```
のように出力されていたが、
これを、
```
命中力 2d+3+{命中修正}
ダメージ 2d+2+{打撃修正}
```
のようにする。
より簡潔にするため。
=> [SW2] 単一部位の魔物はチャットパレットに部位名・攻撃手段を出力しない

_core/lib/sw2/palette-sub.pl
妖精の属性をあらわす能力から生成される妖精魔法のチャットパレットを、より明瞭な文言にする。
```
◯属性：光／魔力５（12）
```
```
属性：光 2d+5
```
```
妖精魔法 2d+5
```
従来も（「魔力」の文言を参照して魔法用のコマンドが生成されるため）コマンド自体は生成されていたが、それは `属性：～ 2d+n` というようなものだった。
しかし、実際のセッション中に妖精魔法を行使させるにあたって、そのときに送信されるメッセージが `属性：～` では、いまひとつ直感的ではないという問題があった。
（とくにテキストセッションにおいて顕著であると思われる）
これを、一般的な（妖精）魔法の能力定義から生成されるものと同様のコマンド（ `妖精魔法 2d+n` ）に改めることで、よりゲーム上の宣言を明瞭にしたい。
=> [SW2] 妖精の属性をあらわす能力から生成される妖精魔法のチャットパレットを、より明瞭にする

_core/lib/sw2/edit-arts.pl
主動作型または常時型においては、公式文献において一般的にリスクは `—` となっている。
以下は該当する例：
- 《ディスエンゲージ》（主動作型、『バトルマスタリー』45頁）
- 《鉄拳鈍輝》（常時型、『バトルマスタリー』47頁）
=> [SW2] 秘伝の「リスク」の入力候補に `—` を追加

_core/lib/sw2/edit-item.pl
=> [SW2] アイテムデータの区分に `武器や防具の強化` を追加

_core/lib/sw2/list-arts.pl, _core/skin/sw2/css/list.css, _core/skin/sw2/list-arts.html
=> [SW2] 魔法・神格・流派の一覧画面でタグを表示する

_core/skin/sw2/css/monster.css
内側の `dl` にもマージンが適用されていた。
結果的として、他の項目間の二倍のマージンがとられていた。
=> [SW2] Fix: 閲覧画面において、騎獣の価格と適正レベルのあいだのマージンが二重に存在していたのを修正

_core/lib/sw2/edit-item.pl
具体的には以下のふたつ：
- `（非売品）`（『アーケインレリック』82頁〈アステリアの連刃剣〉など）
- `取引不能`（『アーケインレリック』80頁〈ティダンの穿光玉〉など）
=> [SW2] アイテムの「基本取引価格」に入力候補を提供

_core/skin/sw2/css/item.css, _core/skin/sw2/sheet-item.html
鎧（〈非金属鎧〉〈金属鎧〉）は「用法」をもたないが、これまでは常に「用法」の列が表示されていた。
これは無意味かつ表示上の据わりがわるいので、防具データにおいて「用法」がひとつも指定されていなければ列ごと非表示にする。
=> [SW2] アイテムシートの防具データにおいて「用法」がひとつも設定されていなければ、表示画面で「用法」の列を表示しない

_core/lib/sw2/edit-item.js, _core/lib/sw2/edit-item.pl, _core/lib/sw2/view-item.pl, _core/skin/sw2/css/edit.css, _core/skin/sw2/css/item.css, _core/skin/sw2/sheet-item.html
アイテムシートの武器データに「射程」の列を追加する。
基本ルールブックでは注記によって射程が規定されている（例⇒『Ⅰ』311頁）が、『エピックトレジャリー』においては射程の列が存在する（例⇒同書96頁）。
そのうえで、前者がそのような形式になっているのは、紙面の広さの問題だと考えられる。また、紙面の広さの問題さえなければ、射程の欄を明示的に設けるほうが、注記による規定よりも閲覧の便宜に優れる。
ここでゆとシートのアイテムシートについて考えると、面積（幅）にはいくらかの余裕があり、またウェブページであるため仮に（非常に長い文字列がどこかの列に入力されるなどして）折り返しが発生しても大きな問題にならないと思われる。
くわえて、アイテムを自作して運用するようなユーザーならびにセッションは、『エピックトレジャリー』を採用している蓋然性が高いと推測されることから、どちらかといえば『エピックトレジャリー』に合わせておくほうが好ましいとも考えられる。
カテゴリの文字列に `投擲`, `ボウ`, `クロスボウ`, `ガン` のいずれかが含まれていれば、武器データの部分において、「射程」の列を表示する。そうでなければ、射程の列を表示しない。
なお、入力候補については、『エピックトレジャリー』に掲載されている〈投擲〉〈ボウ〉〈クロスボウ〉〈ガン〉の射程を網羅するかたちをとった。
カテゴリの文字列に `投擲`, `ボウ`, `クロスボウ`, `ガン` のいずれかが含まれており、かつ、いずれかひとつ以上の用法において「射程」が入力されていたなら、「射程」の列を表示する。そうでなければ、射程の列を表示しない。
〈アックス〉と〈投擲〉双方の機能をあわせもつ武器などで、射程が不要な用法がある場合（この例でいえば〈アックス〉のほう）場合は、その入力値が空であれば、閲覧画面では `―` を表示する。 …
=> [SW2] アイテムデータのカテゴリが〈投擲〉〈ボウ〉〈クロスボウ〉〈ガン〉のいずれかであれば、武器データに「射程」の項目を設ける

_core/lib/sw2/edit-mons.js, _core/lib/sw2/edit-mons.pl, _core/skin/sw2/css/monster.css
魔物データの部位数と内訳（※次の画像の部分）の入力を自動的におこなうように。
大半のケースにおいては上のステータスセクション（攻撃方法や命中力などを入力する箇所）に入力するものと一致するにもかかわらず、手動で（重複的な）入力を要求されていたのを解消するため。
（ようするに、ステータスセクションに「牙（胴体）」「翼（翼）」「翼（翼）」と入力したなら、自動的に、部位数は「 3」 、部位内訳は「胴体／翼×2」になってほしい、という意味）
「攻撃方法（部位）」欄を参照する。
ステータス欄に作られている部位の数をそのまま部位数とする。
`攻撃方法（部位）` 形式で記述されていることを前提に、 `（部位）` の部分を抽出する。
前述の“部位名”を `／` で連結する。
同名の部位が連続して存在する場合（「ドレイク（竜形態）」（⇒『モンストラスロア』77頁）の「翼」「翼」のような場合）、それを `×n` （ _n_ はその名称の部位の数）の形式でまとめる。
上述の自動入力をデフォルトの挙動とするが、（従来同様の）手動入力を可能とするオプションも提供している。
部位数と内訳の入力欄の上にある「部位数と内訳を自動入力する」にチェックを入れると、自動入力が無効化され、手動で入力できるようになる。（※このチェックを入れるまでは、これらのフィールドは _readonly_ となっている）
大半のケースは自動入力で解決できるはずだが、「ヒドラ」（⇒『モンストラスロア』114頁）のように変則的な部位の規定をもつ場合には、手動入力オプションをもちいる想定である。
以降、新規に作成するときは、自動入力がデフォルトである。
既存データは、その内容にかかわらず、手動入力オプションの有効相当で動作する。
この後方互換性のために、_core/lib/sw2/edit-mons.pl_ …
=> [SW2] 魔物データの部位数と内訳の入力を自動化する

_core/lib/sw2/edit-chara.js, _core/skin/sw2/css/chara.css, _core/skin/sw2/css/edit.css
編集画面において、能力値決定のＡ～Ｆそれぞれのとりうる範囲を表示する。
「ポイント割り振りによるキャラクター作成」ルールの運用時においては、各値のとりうる範囲を意識する必要があるが、従来は視覚的に確認できなかった。
（不足または超過ではエラー表示がされるが、どこからがエラーになるのかわからなかった）
これをより直接的に目視で確認できるようにする。
=> [SW2] 能力値Ａ～Ｆのとりうる範囲を明示する

_core/lib/sw2/view-chara.pl
防具の「回避」の欄が正の値であれば、数字の前に `+` をつけるように。
公式文書のアイテムデータでは、防具の回避力修正が正の値のときは、プラス記号が付記されている。
（例：『Ⅰ』317頁〈ポイントガード〉、同319頁〈カイトシールド〉など）
サンプルキャラクターのデータを見るかぎり、キャラクターシート上でも同様である。
（例：『Ⅰ』31頁の〈バックラー〉の欄）
上記をふまえ、公式文書の表記により近づけるようにする。
**before**
**after**
=> [SW2] キャラクターの防具の回避力修正が正の値であれば `+` をつける

_core/lib/json.pl, _core/lib/sw2/json-sub.pl, _core/lib/sw2/subroutine-sw2.pl, _core/skin/_common/js/sheet.js
従来は対象環境を問わず、複数部位の魔物データを出力するとき、その防護点は `メモ` というキーに対する値に設定されていた。
例：
``` 
{
"メモ": "防護:獅子頭9／山羊頭8／竜頭10／胴体6／翼8"
}
```
（これはゆとチャ.adv向けのフォーマットだと思われる）
ところが、 Udonarium におけるインベントリ（ユニット一覧的なもの）等のＵＩでは、インベントリ側で設定した項目しか表示されないという挙動をする。
（表示項目に「防護」が含まれているが、（複数部位であるところの）キマイラのデータにはそのような項目がない）
ここで、「メモ」を表示項目に含めればむろんそれは表示されるのであるが、「メモ」はきわめて普遍的なラベルであり、他の用途に使われることも考えられる。
そのようなさまざまな情況を考慮するに、 Udonarium においては、複数部位のキャラクターであっても、単一部位のキャラクターと共通して「防護」の項目によって防護点を確認できるほうが、現実的な便宜に適うと考える。
よって、 Udonarium にかぎり、以下のような出力をするように変更した。
``` 
{
"防護": "獅子頭9／山羊頭8／竜頭10／胴体6／翼8"
}
```
（見てのとおりキマイラくらい長いと途切れて見えるのだが、これはもうゆとシ側からはどうしようもないので、このまま使うか手動で「獅9／山8／竜10／胴6／翼8」や「9/8/10/6/8」などに調整してもらうしかない。また、このように大した量のテキストを表示できない有り様なので、「メモ」欄に防護点とほかの内容を合わせて記入するようなことは現実的ではない）
---
対称性のため、ココフォリア向けの JSON を得る際にもパラメータ `target=ccforia` を指定するようにしてある。 …
=> [SW2] 複数部位の魔物データを Udonarium 向けに出力する際の、防護点を記述する項目の名称を変更

_core/lib/sw2.0/edit-chara.pl, _core/lib/sw2/edit-chara.js, _core/lib/sw2/edit-chara.pl
アイテム名の山括弧 〈〉 を入力補完（ _datalist_ ）から入力した（っぽい）とき、キャレットを括弧の内側へと自動的に移動する。
いちいち一文字分（ `〈〉[刃][打]` のようなケースなら数文字分）手動でもどるのがだいぶ面倒だったため。
入力補完なんだからキャレットの位置もいい感じに整えてほしくなった。（ゆとチャadv.のタグ挿入がそうであるように）
=> [SW2] アイテム名の山括弧を入力補完から入力したとき、キャレットを括弧内に移動する

_core/lib/sw2.0/edit-chara.pl, _core/lib/sw2/calc-chara.pl, _core/lib/sw2/edit-chara.js, _core/lib/sw2/edit-chara.pl, _core/lib/sw2/subroutine-sw2.pl, _core/lib/sw2/view-chara.pl, _core/skin/sw2/css/chara.css
「武器または装飾品による、回避力または防護点の上昇」を機械的に解決する記法を追加
（なに言ってるのかよくわからなかったら、一番下にある「例」を見てください）
これまでは、回避力および防護点の算出において、「防具でも定義済みで自動計算されるもの（種族特徴や戦闘特技など）でもないもの」を機械的に取り扱う真っ当な方法がなかった。
（防具の一種として記入するような、強引な方法はあった）
しかし、（本質的に一時的効果である練技や賦術などはともかく、）武器や装飾品がもつ常在的な効果は、実際のゲームプレイ上ではほぼ常に適用されるものとみなしてよいケースが多い。
（わかりやすい一例として〈ブラックベルト〉（⇒『エピックトレジャリー』147頁を取り上げると、このアイテムをプレイ中に着脱するような運用をすることは非常に稀である）
このような、“実質的には常時効果として計算してしまっても（まあ防具と同じくらいには）問題がない”ものを取り扱えるようにしたい。
（防具の一種として強引に記入する場合、武器や装飾品の欄と防具欄とで、重複記入になるという問題もあったので、それも避けたかった）
なお、種族特徴によって装飾品の変更が容易な「レプラカーン」で起こるような、現実的に着脱を想定したキャラクター（運用）の場合には、この機能をもちいずに従来どおりの（＝シート外での）管理をする、という想定である。
| 区分 | 回避力 | 防護点 |
|-|-|-|
| 武器    |〈マンゴーシュ〉|〈クォータースタッフ〉等|
| 装飾品 | 該当なし             |〈ブラックベルト〉等|
回避力判定への恒常的な恩恵は、防護点のそれとくらべると稀であるが、〈マンゴーシュ〉（⇒『エピックトレジャリー』114頁）という実例があることと、ゆとシート上ではひとまとめに表示されていることから、対称性も考慮して対応して …
=> [SW2] 武器／装飾品による回避力／防護点の上昇を機械的に解決する記法を追加

_core/lib/sw2/view-chara.pl, _core/skin/sw2.0/sheet-chara.html, _core/skin/sw2/css/chara.css, _core/skin/sw2/sheet-chara.html
一般技能の合計レベルについて、編集画面では表示されていたが、閲覧画面では表示されていなかった。
他のプレイヤーのシートを確認する場合においては、閲覧画面で表示されているほうが都合がよいので、閲覧画面でも表示することにする。
**表示例**
=> [SW2] 閲覧画面でも一般技能の合計レベルを表示する

_core/lib/sw2/edit-arts.js, _core/lib/sw2/edit-arts.pl, _core/lib/sw2/view-arts.pl, _core/skin/sw2/css/arts.css, _core/skin/sw2/sheet-arts.html
技芸シートの魔装データに「人間形態時」の項目を設ける
『バルバロスレイジ』掲載の魔装データの様式（⇒同書53頁）に合わせる。
入力側はラジオボタンによる選択制とした。
項目の性質上、「有効」か「無効」か「変身しない種族用の魔装ゆえに関与しない」かの三値以外をとるとは考えづらいため。
「変身しない種族用の魔装ゆえに関与しない」用の選択肢に対応する値を空としているので、既存データは「変身しない種族用の魔装ゆえに関与しない」相当となる。
これは、閲覧画面での表示では `―` となるため、既存の（変身する種族用の）データに表示されても、大きな問題はないと思われる。
……というか、2024/11/03現時点で、ゆと工公式のゆとシートで魔装データを検索して２件しかヒットしないので、そもそも魔装データが世に気にするほど存在していないような気がします。
実例として、既存の魔装【巨大な身体】（⇒『バルバロスレイジ』56頁）と同様の内容を入力してみる：
=> [SW2] 魔装データに「人間形態時」の項目を追加

_core/lib/dx3/edit-chara.js, _core/skin/dx3/css/edit.css
編集画面において、技能に消費されている経験点の小計が 0 より小さいとき、当該小計値の文字色を変える。
ルールに照らしての誤りに、より気づきやすくするため。
=> [DX3] 編集画面において、技能に消費された経験点の小計が 0 未満のとき、小計の色を変える

_core/lib/sw2/list-mons.pl
騎獣リストにおいて、「購入」「レンタル」それぞれの価格の定義がないものは `―` として表示するように。
従来は単純に空文字列のまま表示され、結果として下の画像のようになっていた。
これはあきらかに不自然で、記入漏れや誤植、ないしは表示の誤りなどを疑いかねない。
なので、なんらかの「購入・レンタルができないこと」を示す表現に改める必要があった。
~~`―` のように表示することも考えたが、購入またはレンタルの価格が入力されないケースはおそらくそれを実行させないケースなので、 `不可` のほうが実態に則している……ような気がする。~~
~~`不可` だとたくさん並んだときの圧がつよいので、やっぱり `―` のほうが無難かもしれない。（でも記入のない騎獣データがそんなに大量に並ぶこともないかもしれない）~~
ゆと工公式にある騎獣データをざっと眺めたかぎり、価格が記入されていないケースは、「単純な記入漏れっぽい」「ルールブック記載の内容と同一なので省略された」「専有騎獣のデータなので購入した前提で購入価格のみを記入してレンタル価格を空欄にする」などがあるもよう。
=> [SW2] 騎獣リストにおいて、購入／レンタルそれぞれの価格の定義がないものは `―` として表示する

_core/lib/sw2/edit-arts.js, _core/lib/sw2/edit-arts.pl
従来は、データの種別にかかわらず常に「魔法データ」と表示されていた。
魔法データを選択していない状態では、これは事実に反するので、選択状況に応じて当該箇所のテキストが変化するように。
- 未選択状態：（修飾なしの）`データ`
- 魔法： `魔法データ`
- 神格： `神格データ`
- 流派： `流派データ`
=> [SW2] Fix: 魔法／神格／流派シートの編集画面において、ヘッダメニュー内の表記をデータ種別に応じて変化させる

_core/lib/sw2/edit-arts.pl
具体的な内容は、『バトルマスタリー』掲載流派をふまえて、以下の考えのもとに用意した。
- ファイター技能
- グラップラー技能
- フェンサー技能
- バトルダンサー技能
- シューター技能
「フェンサー技能」「バトルダンサー技能」については、『バトルマスタリー』内にこれらの単一の技能を要求する秘伝は存在しないが、対称性の観点と、“特定の技能での利用を前提とした流派”というのはごく自然に作成されるだろうと想定されることから、用意してある。
- ファイター技能 or バトルダンサー技能
- ファイター技能 or フェンサー技能 or バトルダンサー技能
- フェンサー技能 or バトルダンサー技能
いずれも『バトルマスタリー』内に存在する。
「ファイター技能 or バトルダンサー技能」は、“重い武器をあつかうような秘伝”が想定される。実例は《激怒セシ熊ノ一撃》（⇒『バトルマスタリー』43頁）など。
「ファイター技能 or フェンサー技能 or バトルダンサー技能」は、“通常の近接武器をあつかう秘伝一般”というニュアンス。実例は《怒レル熊ノ一撃》（⇒『バトルマスタリー』43頁）など。
「フェンサー技能 or バトルダンサー技能」は、“身軽な戦士があつかう秘伝”が想定される。実例は《見えざる敵に苛立て》（⇒『バトルマスタリー』65頁）など。
【スホルテン騎乗戦技】（⇒『バトルマスタリー』61頁）の秘伝に見られる。
「ファイター技能 or フェンサー技能 or バトルダンサー技能」と書くのと何が違うのかいまいち定かではないが、同流派はライダー技能を念頭においたものであり具体的な戦士系技能の名称を挙げるよりも「近接攻撃武器」としたほうが直感的っぽいことと、戦士系技能をもたない騎手が当該秘伝をもちいる場合（※それでも騎獣に恩恵がある）が考慮されているのではないかと思われる。 …
=> [SW2] 秘伝の「使用」欄に入力候補を提供

_core/lib/dx3/edit-chara.pl
_input_ 側の _list_ 属性はなぜか元から記述されていたので、 _datalist_ を追加したのみ
=> [DX3] ヴィークルの「種別」に入力候補を提供

_core/lib/sw2/edit-mons.js, _core/lib/sw2/edit-mons.pl
コア部位の入力欄において、部位内訳にもとづいて入力候補を提供する
大多数の場合、コア部位は部位内訳に含まれるいずれかの部位に相当する字句となるはずなので、（すでに別途入力されているはずの）部位内訳を利用して、コア部位の入力を省力化したい
基本的には、部位内訳の入力内容を `／` で分割し、その各項を入力候補とする。
このとき、同名の部位が複数あった場合（例： `翼×2` など）は、その部位名＋ `（すべて）` のかたちで入力候補とする。（複数ある部位がコア部位とされるとき、たいていの場合は“すべて”であることから）
また、コア部位をもたない魔物を考慮して、 `なし` という候補も提供する。
以下の「具体例」も参照のこと。
「スカイホエール」（⇒『モンストラスロア』112頁）
- 部位内訳：頭部／胴体／尾びれ
- 入力候補：
- なし
- 頭部
- 胴体
- 尾びれ
- 実際のコア部位：頭部
「ドラゴネット」（⇒『モンストラスロア』175頁）
- 部位内訳：胴体／翼×2
- 入力候補：
- なし
- 胴体
- 翼（すべて）
- 実際のコア部位：胴体
「ケルベロス」（⇒『モンストラスロア』203頁）
- 部位内訳：頭部×3／胴体
- 入力候補：
- なし
- 頭部（すべて）
- 胴体
- 実際のコア部位：頭部（すべて）
これらのような場合は、手動で入力するしかない
「キマイラ」（⇒『モンストラスロア』173頁）
- 部位内訳：獅子頭／山羊頭／竜頭／胴体／翼
- 入力候補：
- なし
- 獅子頭
- 山羊頭
- 竜頭
- 胴体
- 翼
- 実際のコア部位：頭（すべて）
※『モンストラスロア』時点で該当するのは「キマイラ」のみであり、きわめて稀
「グリーントーチ」（⇒『モンストラスロア』125頁）
- 部位内訳：根／雄しべ／花弁×6
- 入力候補：
- なし
- 根
- 雄しべ …
=> [SW2] 魔物データのコア部位入力欄において、部位内訳にもとづく入力候補を提供する

_core/lib/sw2/edit-arts.pl
魔装の「適用部位」に入力候補を提供するように。
---
具体的な内容は、『バルバロスレイジ』をもとに、
普遍的な表現：
- `―`
- すべて
- コア部位
- その他部位
- その他部位すべて
（『バルバロスレイジ』掲載の魔装データにあるもの）
具体的な部位名：
- 頭部
- 胴体
- 上半身
- 翼
- 邪眼
- 蠍
- 鋏
（『バルバロスレイジ』58頁の部位定義より）
とした。
なお、このうち、「頭部」「上半身」「翼」については『バルバロスレイジ』の個別魔装データには存在しないが、対称性の観点からリストに入れることにした。
---
備考：
_input_ 側には _list_ 属性がもともと指定されていたが、当該 id をもつ _datalist_ が存在しなかった。（ので、 _datalist_ だけを追加している）
=> [SW2] 魔装データの「適用部位」に入力候補を提供

_core/lib/sw2/edit-arts.pl
before: `カテゴリ・プレイヤー名`
after: `カテゴリ・製作者名`
（魔法／神格／流派シートにおいて、「プレイヤー」名を入力する項目はなく、あるのは「製作者」名を入力する項目である）
=> [SW2] 魔法／神格／流派シートの編集画面の目次の項目名を修正

_core/lib/sw2/palette-sub.pl
https://github.com/yutorize/ytsheet2/pull/138 にて【カオスエクスプロージョン】用の威力コマンドが生成されるようになったが、その条件がさすがに妥当でなさすぎたのを修正。
https://github.com/yutorize/ytsheet2/pull/138 時点では「ランク10以上であれば」という条件になっており、これは【カオスエクスプロージョン】が行使可能となる15レベル時点の全属性契約の「10＆５」（⇒『メイガスアーツ』128頁）をふまえてのものだと思われるが、ランクしか参照していなかったため、（契約属性にかかわらず）【カオスエクスプロージョン】を行使しえないキャラクターに対しても出力されていた。
（たとえば、“フェアリーテイマー**11レベル**の３属性契約でランク14行使可能”というようなキャラクターでも、ランク14の部分がランク10条件を満たしてしまうため、出力されていた）
いかなる契約であっても行使しえない魔法の威力が出力されるのは明らかに誤りといえるため、レベル15未満の場合は威力80のコマンドを出力しないようにした。
=> [SW2] Fix: 【カオスエクスプロージョン】用のチャットパレットの生成条件を修正

_core/lib/sw2/view-chara.pl
バトルダンサー技能による宣言特技枠の追加では、「この枠で習得した宣言特技は、バトルダンサー技能を用いて命中力判定や回避力判定を行うときに限り、宣言することができます」という制約がつく。（『バトルマスタリー』６頁、右側「宣言特技枠追加」の節、第三段落）
そのため、その戦闘特技が追加枠での習得なのか否かは、キャラクター運用上で意識する必要がある。
しかし、これまでは、閲覧画面では追加枠による習得なのか否かが不明瞭だった。
（編集画面では、追加枠には「1+」のように表示され区別できたが、閲覧画面では「1」としか表示されておらず、通常の１レベルの枠とあいまいだった）
これを改善するために、閲覧画面においても、バトルダンサー技能による追加枠では「1+」のように表示するように変更する。
=> [SW2] 閲覧画面において、バトルダンサー技能による追加特技枠を識別できるように

_core/lib/json.pl
外部のツールやスクリプトで利用する想定
---
副次的に、「エクスポートした JSON だけは手元にあるが、元シートがどこのサーバーだったかわからない」みたいなケースへの助けになるかもしれない
=> JSON 出力時に、シートの URL を含める

_core/lib/json.pl
`viewNotFound` は _view.pl_ 内に定義されているサブルーチンなので、 _json.pl_ から呼び出そうとしてエラーになっていた。
`viewNotFound` の内容を見たところ、 JSON へのアクセス時に必要そうなものではなかったので、単純な `error` サブルーチンで代用することにした。
=> Fix: 存在しない id を指定して JSON にアクセスしようとしたときに内部エラーが発生しないように

_core/lib/palette.pl, _core/lib/sw2/palette-sub.pl
一部の奈落魔法のための、属性抽選用のコマンドをチャットパレットに含める。
該当する奈落魔法は次のとおり：
- ７レベル【アビス・ヴォーテックス】（⇒『アビスブレイカー』13頁）
- 13レベル【アビス・ストーム】（⇒『アビスブレイカー』16頁）
当該魔法は、奈落魔法のラインナップ内において比較的有力な攻撃手段であり、奈落魔法を習得しているキャラクターにおいては、使用頻度がそれなりに高い傾向にあると思われる。
そのため、これら魔法における属性の抽選処理を、より円滑に実行できるようにしたい。
属性を抽選するための抽選コマンド。
各魔法の「拡張効果」を考慮し、２つをいっぺんに抽選するコマンドも提供する。
アビスゲイザー技能が７レベル以上の場合。
攻撃用の威力コマンドの後。
- 「使用ツール」が「ゆとチャadv.」であれば、ゆとチャadv.用の形式で出力する
- 「使用ツール」が「Tekey」または「その他（BCDice使用）」であれば、BCDice用の形式で出力する
```
1$雷,純エネルギー,衝撃,断空,毒,呪い
2$雷,純エネルギー,衝撃,断空,毒,呪い
```
```
choice 雷 純エネルギー 衝撃 断空 毒 呪い
x2 choice 雷 純エネルギー 衝撃 断空 毒 呪い
```
=> [SW2] 奈落魔法の属性抽選用のコマンドをチャットパレットに含める

_core/lib/ar2e/palette-sub.pl
アリアンロッド2Eのデフォルト変数及びプリセット（変数使用）においてすべての判定で変数を使用するように変更。
キャンペーンシナリオ等の理由でキャラクターシート及びチャットパレットの更新を頻繁に行うケースにおいて、チャットパレットの更新漏れを予防する。
また、変数対応によって複数キャラクター間でユーザーオリジナルのチャットパレットのテンプレートを使用しやすくなる。
各種基礎ステータス判定及びトラップ探知以下8種の判定においてデフォルト変数に判定ダイスを追加。
従来キャラクターシートを参照して数値を出力していた部分に対して新規に追加したデフォルト変数を使用する。
キャラクターシートの各種ダイス数の設定に応じて変動する。
```
//トラップ探知ダイス=2
```
```
旧：トラップ探知判定 {トラップ探知}+2D
新：トラップ探知判定 {トラップ探知}+{トラップ探知ダイス}D
```
```
旧：{トラップ探知}+2D トラップ探知判定
新：{トラップ探知}+{トラップ探知ダイス}D トラップ探知判定
```
=> 追加:[AR2E]デフォルト変数及びプリセット（変数使用）において全て変数対応

_core/lib/ar2e/palette-sub.pl
https://github.com/yutorize/ytsheet2/pull/306 の変更の際の記入ミスで
//アイテム鑑定ダイス=+2
等の表記になってる症状の修正。
=> 修正:[AR2E]デフォルト変数のアイテム鑑定ダイスに不要な+記号が含まれている。

_core/lib/sw2/edit-chara.js
武器欄において、「必要精神力」の概念をサポート
『ウルシラ博物誌』掲載の流派【オークファルト念闘術】において、「必要精神力」の概念が規定された。
- 「必要精神力」のルールは、同書27頁の、流派アイテム概説、ならびに、秘伝《念武肢》の効果を参照。
- この概念をもちいる具体的なアイテムデータについては、同書31頁を参照。
武器の「必要筋力」欄で、数値の末尾に `w` が記述されていれば、「必要精神力」を意味するものとみなす。
なお、この書式は、『ウルシラ博物誌』31頁に倣ったもの。
「必要精神力」とみなしたならば、筋力の代わりに精神力を参照し、不足の是非を検証する。
このとき、従来の「必要筋力」に干渉する要素のいっさいを無視する。これは、【オークファルト念闘術】の記述において、そのような要素を考慮する素振りがまったく見られず、また、「必要精神力」は「必要筋力」とは異なるルールであることにもとづく。
JS 内では、「必要精神力」の文脈における“精神力”の表現を _wil_ とした。
これは、『ウルシラ博物誌』31頁の書式において“精神力”の表現が _w_ であることにもとづく。 _w_ が何の略であるのかは定かでないが、 will （意志・意志力・自制心）か wisdom （賢明さ・判断力）のいずれかと思われ、『SW2』における“精神力”の位置づけからは前者であると推測した。
まあ従来どおり _mnd_ でも（のほうが）いいかもしれない。
https://yutorize.2-d.jp/ytsheet/sw2.5/?id=4z1Rw4
=> [SW2] 武器の「必要精神力」の概念をサポート

_core/lib/sw2/palette-sub.pl
半減時にクリティカルさせる効果をもつのは《クリティカルキャスト**Ⅱ**》（⇒『Ⅲ』215頁、『ＢＭ』28頁）のみであり、《クリティカルキャスト**Ⅰ**》（⇒『Ⅱ』233頁、『ＢＭ』28頁）には当該効果がない。
オプション名が `クリティカルキャストⅠ` `クリティカルキャストII` `クリティカルキャスト1` にマッチする場合は、半減時クリティカル効果がないものとして処理する。
ローマ数字の記述されていない無印クリティカルキャストについては、後方互換性の観点から従来どおり、半減時のクリティカル効果があるものとした。
https://yutorize.2-d.jp/ytsheet/sw2.5/?id=rLoMwE
```
真語魔法行使 2d+22+{魔力修正}+{行使修正}
ダメージ k10[{魔法C}]+22+{魔力修正}+{魔法D修正}
ダメージ k20[{魔法C}]+22+{魔力修正}+{魔法D修正}
ダメージ k30[{魔法C}]+22+{魔力修正}+{魔法D修正}
物理ダメージ k30[10]+22+{魔力修正}+{物理魔法D修正}
ダメージ k40[{魔法C}]+22+{魔力修正}+{魔法D修正}
ダメージ k50[{魔法C}]+22+{魔力修正}+{魔法D修正}
ダメージ k60[{魔法C}]+22+{魔力修正}+{魔法D修正}
ダメージ k100[{魔法C}]+22+{魔力修正}+{魔法D修正}
半減 k10[13]+22+{魔力修正}//+{魔法D修正}
半減 k20[13]+22+{魔力修正}//+{魔法D修正}
半減 k30[13]+22+{魔力修正}//+{魔法D修正}
半減 k40[13]+22+{魔力修正}//+{魔法D修正}
半減 k50[13]+22+{魔力修正}//+{魔法D修正}
半減 …
```
=> Fix: [SW2] 《クリティカルキャストⅠ》の場合は半減時にクリティカルさせない

_core/lib/sw2/edit-chara.js
編集画面において、複数部位をもつ種族のコア部位のＨＰまたはＭＰが、 _NaN_ と表示される場合がある。
https://yutorize.2-d.jp/ytsheet/sw2.5/?id=6Ak5SF
直接修正記法によって生命力／精神力が増減していないとき、それぞれＨＰ／ＭＰが NaN となる。
計算過程で、直接修正記法による増減量が参照されていたが、増減がない場合は _undefined_ であるため、数値と _undefined_ とを演算した結果として _NaN_ になっていた。
Null合体演算子をもちいて、 _undefined_ のときは 0 とみなす。
=> Fix: [SW2] 編集画面において、複数部位のＰＣデータのコア部位のＨＰ／ＭＰが NaN になる場合がある不具合を修正

_core/lib/sw2.0/edit-chara.pl, _core/lib/sw2/edit-chara.js, _core/lib/sw2/edit-chara.pl
これらは四桁以上になる数値であり、そうした巨大な数はカンマ区切りのほうが読み取りやすいため。
また、閲覧画面においてはカンマ区切りで表記されることを踏まえ、それに合わせる意図もある。
=> [SW2] 編集画面において、キャラクター作成時点の経験点・ガメル・名誉点をカンマ区切りにする

_core/skin/sw2.0/sheet-chara.html, _core/skin/sw2/css/chara.css, _core/skin/sw2/sheet-chara.html
魔法／賦術／呪歌のいずれにも専用化の影響が介在していなければ、閲覧画面において、「専用」の列を非表示にする。
必要のないものは省略して、より見通しをよくする。
術具の専用化は、
- 「専用化するだけの名誉点ないしは冒険者ランクがない」（一般的な低レベル期）
- 「専用化したところでボーナスに影響しない」（たまたまそのような能力値である場合）
- 「達成値を高める必要がない」（もっぱら補助動作で運用する想定で習得された魔動機術や森羅魔法、賦術などが該当）
などのケースにおいて実施されないこともそれなりにある。
そのような、とくに専用化を実施していないキャラクターにおいては、当該部分における「専用」列は無意味であるため、省略したい。
=> [SW2] 閲覧画面の魔法／賦術／呪歌の基準値について、ひとつも専用化の影響が介在していなければ専用化の列を非表示にする

_core/lib/sw2/palette-sub.pl, _core/lib/sw2/view-chara.pl, _core/skin/sw2/css/chara.css
「用法：1H投」「用法：2H投」の武器の用法にカテゴリを付記する。
- 閲覧画面
- チャットパレット
「nH投」という用法は、（「1H両」／「2H」のようなものとは異なり）、用法によって近接なのか投擲なのかが識別できない。
（これはゲームルールの問題）
そのため、近接にも投擲にももちいることができる「nH投」の武器をあつかうデータでは、それが近接／投擲のいずれであるのかが識別できないという問題がある。
仮に近接と投擲のデータがまったく同一になるのであれば実害はすくないが、実際には、**近接としてもちいる場合と投擲としてもちいる場合とでは属する「カテゴリ」が異なり**（⇒『Ⅰ』298頁）、そして《武器習熟／＊＊》はカテゴリを参照して追加ダメージを与えるため、近接と投擲とで追加ダメージが異なるというケースはそこそこ現実的に生じる。
また、そもそも近接と投擲とで数値設定の異なる武器というのも考えられる。（『Ⅲ』と『エピックトレジャリー』とで内容が異なるため誤植の疑いも濃いが、たとえば『エピックトレジャリー』の〈リマホーク〉（⇒88頁，96頁）は、近接か投擲かによって追加ダメージの値が異なる）
具体例として、[「用法：1H投」であり近接攻撃にも投擲にも使用できる武器〈ハンドアックス〉（⇒『Ⅰ』303頁，311頁）を採用し《武器習熟／アックス》を習得したキャラクターシート](https://yutorize.2-d.jp/ytsheet/sw2.5/?id=I1S31K )を仮定すると、武器欄は次の画像のようになり、二行それぞれが近接／投擲のいずれに対応するのかが定かでなくなる。
これだけであれば備考欄になにかしらを記述することで識別を図ることもできるが、そうした場合においても、チャットパレットには（備考欄は反映されないため）依然として同様の問題が残る。 …
=> [SW2] 「用法：1H投」「用法：2H投」の武器の用法にカテゴリを付記する

_core/lib/sw2/palette-sub.pl
チャットパレットの「非戦闘系」の見出しに、必要に応じ「魔物知識」「先制」の文言を追加する
- 戦闘開始処理における「魔物知識判定」と「先制判定」は、「戦闘」の一部である。（『Ⅰ』128頁）
- 「魔物知識判定」をおこなうのは戦闘中のみとはかぎらないが、すくなくとも戦闘に際しておこなう蓋然性はかなり高い。
- 「先制判定」をおこなうのは常に戦闘中である。
上記をかんがみたとき、魔物知識判定・先制判定のためのコマンドが「非戦闘系」と（のみ）明記されている箇所に存在するのは、すくなからず不適切である。
- ルールに照らして妥当さに欠ける（とくに先制判定）
- コマンドがどこに存在するのかを把握していないような経験の浅いユーザーに対しては、誤導的でもある
- 戦闘に際した魔物知識判定や先制判定のコマンドを探すときに、「非戦闘中」と銘打ってある箇所は探さない可能性がかんがえられる
- とくにゆとチャadv.やTekeyにおいては折り畳みが適用されるため、物理的に視界に入らないことすらありうる
- 魔物知識が 0 でなければ、見出しに `・魔物知識` の文言を追加する
- 先制力が 0 でなければ、見出しに `・先制` の文言を追加する
=> [SW2] チャットパレットの「非戦闘系」の見出しに、必要に応じ「魔物知識」「先制」の文言を追加する

_core/lib/sw2/palette-sub.pl
=> Fix: [SW2.5] 終律のダメージコマンドに付記する文言を「呪歌」から「終律」に変更

_core/lib/sw2/edit-arts.js
複数のカテゴリをもつアイテムを流派装備として流派データに追加したとき、その時点では、次の画像のように、カテゴリが区切られていなかった。（ここで〈クロスボウ〉と〈盾〉が別々の行にあるのは、表示幅の不足による折り返しにすぎない）
保存してリロードすると、次のように水平線で明示的に区切られる。
JS側では複数のカテゴリをもつ可能性が考慮されていなかった。
=> Fix: [SW2] 流派データに流派装備を追加した時点では、当該アイテムが複数のカテゴリをもつ可能性が考慮されていない不具合を修正

_core/skin/sw2.0/sheet-chara.html, _core/skin/sw2/css/chara.css, _core/skin/sw2/sheet-chara.html
所持金が空のとき、単位「G」のみが表示されてしまう。
所持金が空になるケースとは、自動計算を無効化したうえで直接入力の値を空文字列としている状態が該当する。
（所持金を管理するつもりのないＮＰＣなどにおいては、このような用法がありうる）
再現サンプル： https://yutorize.2-d.jp/ytsheet/sw2.5/?id=2yAo8Y
=> Fix: [SW2] 閲覧画面において、所持金が空のときに単位「G」のみが表示されてしまう現象を修正
